import os
from pathlib import Path

from PyQt5.QtCore import Qt, QSize
from PyQt5.QtGui import (
    QColor,
    QIcon,
    QImage,
    QPainter,
    QPainterPath,
    QPalette,
    QPen,
    QPixmap,
)

PROJECT_DIR = Path(__file__).resolve().parent.parent
PLACE_IMAGE_DIR = PROJECT_DIR / "place_images"
DEFAULT_IMAGE_DIR = PROJECT_DIR / "db-server"
STAMP_QR_URL = "https://travel-jc.onrender.com/"
STAMP_POSTER_IMAGE = PROJECT_DIR / "poster.png"

_IMAGE_PIXMAP_CACHE = {}
_IMAGE_PIXMAP_CACHE_MAX = 320

LANGUAGES = [
    "한국어",
    "English",
    "日本語",
    "简体中文",
    "繁體中文",
    "Deutsch",
    "Nederlands",
    "Svenska",
    "Français",
    "Italiano",
    "Español",
    "Português",
    "Русский",
    "Polski",
    "Čeština",
    "Українська",
    "Lietuvių",
    "Latviešu",
]

LANG_INFO = {
    "한국어": {
        "flags": "KR",
        "language_title": "언어",
        "tour": "추천코스",
        "route": "관광/맛집",
        "qr": "QR",
        "open": "열기",
        "route_input_title": "목적지 입력",
        "route_input_hint": "키보드를 눌러 목적지를 입력하세요.",
        "route_back": "뒤로",
        "route_result_title": "랜드마크 정보",
        "route_result_label": "랜드마크: {text}",
        "route_keyboard_space": "공백",
        "route_keyboard_back": "삭제",
        "route_keyboard_clear": "초기화",
        "route_keyboard_enter": "확인",
        "route_category_food": "음식",
        "route_category_landmark": "랜드마크",
        "route_category_restroom": "화장실",
        "route_category_info": "관광안내소",
        "food_category_title": "음식 카테고리",
        "food_korean": "한식",
        "food_snack": "분식",
        "food_cafe": "카페/디저트",
        "food_fast": "패스트푸드",
        "food_japanese": "일식",
        "food_chinese": "중식",
        "food_western": "양식",
        "food_convenience": "편의점/간식",
        "food_vegan": "채식/비건",
        "food_bar": "주점/펍",
    },
    "English": {
        "flags": "US",
        "language_title": "Language",
        "tour": "Recommended Courses",
        "route": "Sights & Eats",
        "qr": "QR",
        "open": "Open",
        "route_input_title": "Destination Input",
        "route_input_hint": "Tap keyboard to enter destination.",
        "route_back": "Back",
        "route_result_title": "Route Guidance",
        "route_result_label": "Destination: {text}",
        "route_keyboard_space": "Space",
        "route_keyboard_back": "Back",
        "route_keyboard_clear": "Clear",
        "route_keyboard_enter": "Enter",
        "route_category_food": "Food",
        "route_category_landmark": "Landmarks",
        "route_category_restroom": "Restrooms",
        "route_category_info": "Tourist Info",
        "food_category_title": "Food Categories",
        "food_korean": "Korean",
        "food_snack": "Street Food",
        "food_cafe": "Cafe/Dessert",
        "food_fast": "Fast Food",
        "food_japanese": "Japanese",
        "food_chinese": "Chinese",
        "food_western": "Western",
        "food_convenience": "Convenience/Snacks",
        "food_vegan": "Vegetarian/Vegan",
        "food_bar": "Bar/Pub",
    },
    "日本語": {
        "flags": "JP",
        "language_title": "言語",
        "tour": "おすすめコース",
        "route": "観光/グルメ",
        "qr": "QR",
        "open": "開く",
        "route_input_title": "目的地入力",
        "route_input_hint": "キーボードをタップして目的地を入力してください。",
        "route_back": "戻る",
        "route_result_title": "道案内",
        "route_result_label": "目的地: {text}",
        "route_keyboard_space": "スペース",
        "route_keyboard_back": "削除",
        "route_keyboard_clear": "クリア",
        "route_keyboard_enter": "決定",
    },
    "简体中文": {
        "flags": "CN",
        "language_title": "语言",
        "tour": "推荐路线",
        "route": "景点/美食",
        "qr": "QR",
        "open": "打开",
        "route_input_title": "目的地输入",
        "route_input_hint": "点击键盘输入目的地。",
        "route_back": "返回",
        "route_result_title": "路线指引",
        "route_result_label": "目的地: {text}",
        "route_keyboard_space": "空格",
        "route_keyboard_back": "退格",
        "route_keyboard_clear": "清空",
        "route_keyboard_enter": "确定",
    },
    "繁體中文": {
        "flags": "TW",
        "language_title": "語言",
        "tour": "推薦路線",
        "route": "景點/美食",
        "qr": "QR",
        "open": "開啟",
        "route_input_title": "目的地輸入",
        "route_input_hint": "點擊鍵盤輸入目的地。",
        "route_back": "返回",
        "route_result_title": "路線指引",
        "route_result_label": "目的地: {text}",
        "route_keyboard_space": "空格",
        "route_keyboard_back": "退格",
        "route_keyboard_clear": "清除",
        "route_keyboard_enter": "確認",
    },
    "Deutsch": {
        "flags": "DE",
        "language_title": "Sprache",
        "tour": "Empfohlene Routen",
        "route": "Sehenswertes & Essen",
        "qr": "QR",
        "open": "Öffnen",
        "route_input_title": "Ziel eingeben",
        "route_input_hint": "Tippen Sie auf die Tastatur, um das Ziel einzugeben.",
        "route_back": "Zurück",
        "route_result_title": "Routenführung",
        "route_result_label": "Ziel: {text}",
        "route_keyboard_space": "Leerzeichen",
        "route_keyboard_back": "Löschen",
        "route_keyboard_clear": "Leeren",
        "route_keyboard_enter": "Bestätigen",
    },
    "Nederlands": {
        "flags": "NL",
        "language_title": "Taal",
        "tour": "Aanbevolen routes",
        "route": "Bezienswaardigheden & eten",
        "qr": "QR",
        "open": "Openen",
        "route_input_title": "Bestemming invoeren",
        "route_input_hint": "Tik op het toetsenbord om de bestemming in te voeren.",
        "route_back": "Terug",
        "route_result_title": "Routebegeleiding",
        "route_result_label": "Bestemming: {text}",
        "route_keyboard_space": "Spatie",
        "route_keyboard_back": "Verwijder",
        "route_keyboard_clear": "Wissen",
        "route_keyboard_enter": "Bevestigen",
    },
    "Svenska": {
        "flags": "SE",
        "language_title": "Språk",
        "tour": "Rekommenderade rutter",
        "route": "Sevärdheter & mat",
        "qr": "QR",
        "open": "Öppna",
        "route_input_title": "Ange destination",
        "route_input_hint": "Tryck på tangentbordet för att ange destination.",
        "route_back": "Tillbaka",
        "route_result_title": "Vägbeskrivning",
        "route_result_label": "Destination: {text}",
        "route_keyboard_space": "Mellanslag",
        "route_keyboard_back": "Backsteg",
        "route_keyboard_clear": "Rensa",
        "route_keyboard_enter": "Bekräfta",
    },
    "Français": {
        "flags": "FR",
        "language_title": "Langue",
        "tour": "Parcours recommandés",
        "route": "Sites & restos",
        "qr": "QR",
        "open": "Ouvrir",
        "route_input_title": "Saisir la destination",
        "route_input_hint": "Appuyez sur le clavier pour saisir la destination.",
        "route_back": "Retour",
        "route_result_title": "Guidage",
        "route_result_label": "Destination : {text}",
        "route_keyboard_space": "Espace",
        "route_keyboard_back": "Supprimer",
        "route_keyboard_clear": "Effacer",
        "route_keyboard_enter": "Valider",
    },
    "Italiano": {
        "flags": "IT",
        "language_title": "Lingua",
        "tour": "Percorsi consigliati",
        "route": "Attrazioni & cibo",
        "qr": "QR",
        "open": "Apri",
        "route_input_title": "Inserisci destinazione",
        "route_input_hint": "Tocca la tastiera per inserire la destinazione.",
        "route_back": "Indietro",
        "route_result_title": "Indicazioni",
        "route_result_label": "Destinazione: {text}",
        "route_keyboard_space": "Spazio",
        "route_keyboard_back": "Cancella",
        "route_keyboard_clear": "Pulisci",
        "route_keyboard_enter": "Conferma",
    },
    "Español": {
        "flags": "ES",
        "language_title": "Idioma",
        "tour": "Rutas recomendadas",
        "route": "Atracciones y comida",
        "qr": "QR",
        "open": "Abrir",
        "route_input_title": "Ingresar destino",
        "route_input_hint": "Toque el teclado para introducir el destino.",
        "route_back": "Atrás",
        "route_result_title": "Guía de ruta",
        "route_result_label": "Destino: {text}",
        "route_keyboard_space": "Espacio",
        "route_keyboard_back": "Borrar",
        "route_keyboard_clear": "Limpiar",
        "route_keyboard_enter": "Aceptar",
    },
    "Português": {
        "flags": "PT",
        "language_title": "Idioma",
        "tour": "Rotas recomendadas",
        "route": "Atrações e comida",
        "qr": "QR",
        "open": "Abrir",
        "route_input_title": "Inserir destino",
        "route_input_hint": "Toque no teclado para inserir o destino.",
        "route_back": "Voltar",
        "route_result_title": "Orientação de rota",
        "route_result_label": "Destino: {text}",
        "route_keyboard_space": "Espaço",
        "route_keyboard_back": "Apagar",
        "route_keyboard_clear": "Limpar",
        "route_keyboard_enter": "Confirmar",
    },
    "Русский": {
        "flags": "RU",
        "language_title": "Язык",
        "tour": "Рекомендуемые маршруты",
        "route": "Достопримечательности и еда",
        "qr": "QR",
        "open": "Открыть",
        "route_input_title": "Ввод пункта назначения",
        "route_input_hint": "Нажмите на клавиатуру, чтобы ввести пункт назначения.",
        "route_back": "Назад",
        "route_result_title": "Маршрут",
        "route_result_label": "Пункт назначения: {text}",
        "route_keyboard_space": "Пробел",
        "route_keyboard_back": "Удалить",
        "route_keyboard_clear": "Очистить",
        "route_keyboard_enter": "Подтвердить",
    },
    "Polski": {
        "flags": "PL",
        "language_title": "Język",
        "tour": "Polecane trasy",
        "route": "Atrakcje i jedzenie",
        "qr": "QR",
        "open": "Otwórz",
        "route_input_title": "Wprowadź cel",
        "route_input_hint": "Dotknij klawiatury, aby wprowadzić cel.",
        "route_back": "Wstecz",
        "route_result_title": "Nawigacja",
        "route_result_label": "Cel: {text}",
        "route_keyboard_space": "Spacja",
        "route_keyboard_back": "Usuń",
        "route_keyboard_clear": "Wyczyść",
        "route_keyboard_enter": "Potwierdź",
    },
    "Čeština": {
        "flags": "CZ",
        "language_title": "Jazyk",
        "tour": "Doporučené trasy",
        "route": "Památky a jídlo",
        "qr": "QR",
        "open": "Otevřít",
        "route_input_title": "Zadat cíl",
        "route_input_hint": "Klepněte na klávesnici a zadejte cíl.",
        "route_back": "Zpět",
        "route_result_title": "Navigace",
        "route_result_label": "Cíl: {text}",
        "route_keyboard_space": "Mezera",
        "route_keyboard_back": "Smazat",
        "route_keyboard_clear": "Vymazat",
        "route_keyboard_enter": "Potvrdit",
    },
    "Українська": {
        "flags": "UA",
        "language_title": "Мова",
        "tour": "Рекомендовані маршрути",
        "route": "Пам'ятки та їжа",
        "qr": "QR",
        "open": "Відкрити",
        "route_input_title": "Введення пункту призначення",
        "route_input_hint": "Натисніть клавіатуру, щоб ввести пункт призначення.",
        "route_back": "Назад",
        "route_result_title": "Маршрут",
        "route_result_label": "Пункт призначення: {text}",
        "route_keyboard_space": "Пробіл",
        "route_keyboard_back": "Видалити",
        "route_keyboard_clear": "Очистити",
        "route_keyboard_enter": "Підтвердити",
    },
    "Lietuvių": {
        "flags": "LT",
        "language_title": "Kalba",
        "tour": "Rekomenduojami maršrutai",
        "route": "Lankytinos vietos ir maistas",
        "qr": "QR",
        "open": "Atidaryti",
        "route_input_title": "Įvesti tikslą",
        "route_input_hint": "Palieskite klaviatūrą ir įveskite tikslą.",
        "route_back": "Atgal",
        "route_result_title": "Maršrutas",
        "route_result_label": "Tikslas: {text}",
        "route_keyboard_space": "Tarpas",
        "route_keyboard_back": "Trinti",
        "route_keyboard_clear": "Išvalyti",
        "route_keyboard_enter": "Patvirtinti",
    },
    "Latviešu": {
        "flags": "LV",
        "language_title": "Valoda",
        "tour": "Ieteiktie maršruti",
        "route": "Apskates vietas un ēdiens",
        "qr": "QR",
        "open": "Atvērt",
        "route_input_title": "Ievadīt galamērķi",
        "route_input_hint": "Pieskarieties tastatūrai, lai ievadītu galamērķi.",
        "route_back": "Atpakaļ",
        "route_result_title": "Maršruts",
        "route_result_label": "Galamērķis: {text}",
        "route_keyboard_space": "Atstarpe",
        "route_keyboard_back": "Dzēst",
        "route_keyboard_clear": "Notīrīt",
        "route_keyboard_enter": "Apstiprināt",
    },
}

UI_TRANSLATIONS = {
    "en": {
        "location_label": "Location",
        "food_category_title": "Food Categories",
        "route_category_food": "Food",
        "route_category_landmark": "Landmarks",
        "route_category_restroom": "Restrooms",
        "route_category_info": "Tourist Info",
        "food_no_menus": "No menus available.",
        "food_no_foods": "No foods available.",
        "food_select_prompt": "Select a food to see details",
        "food_restaurant_info": "Restaurant Info",
        "food_full_menu": "Full Menu",
        "food_no_description": "No description",
        "food_no_additional_info": "No additional info.",
        "food_no_menu_info": "No menu info",
        "food_price_label": "Price",
        "food_restaurants_title": "Restaurants",
        "food_no_restaurants": "No restaurants available.",
        "food_restaurant_label": "Restaurant",
        "food_hours_label": "Hours",
        "food_phone_label": "Phone",
        "food_reservation_label": "Reservation",
        "food_address_label": "Address",
        "food_menu_fallback": "Menu",
        "place_fallback": "Place {id}",
        "landmarks_empty": "No landmarks available.",
        "route_qr_unavailable": "QR unavailable.",
        "route_map_unavailable": "Map unavailable.",
        "route_no_image": "No image.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Travel Stamp",
        "travel_stamp_line1": "Scan the QR to start your stamp tour.",
        "travel_stamp_line2": "Collect stamps as you visit attractions.",
        "travel_stamp_line3": "Complete missions to earn rewards.",
        "travel_stamp_qr_hint": "Scan to join",
    },
    "ko": {
        "location_label": "위치",
        "food_category_title": "음식 카테고리",
        "route_category_food": "음식",
        "route_category_landmark": "관광지",
        "route_category_restroom": "화장실",
        "route_category_info": "관광안내",
        "food_no_menus": "메뉴가 없습니다.",
        "food_no_foods": "표시할 음식이 없습니다.",
        "food_select_prompt": "음식을 선택하면 상세 정보가 표시됩니다.",
        "food_restaurant_info": "가게 정보",
        "food_full_menu": "전체 메뉴",
        "food_no_description": "설명 없음",
        "food_no_additional_info": "추가 정보가 없습니다.",
        "food_no_menu_info": "메뉴 정보 없음",
        "food_price_label": "가격",
        "food_restaurants_title": "식당",
        "food_no_restaurants": "식당이 없습니다.",
        "food_restaurant_label": "가게",
        "food_hours_label": "영업시간",
        "food_phone_label": "전화",
        "food_reservation_label": "예약",
        "food_address_label": "주소",
        "food_menu_fallback": "메뉴",
        "place_fallback": "장소 {id}",
        "landmarks_empty": "관광지가 없습니다.",
        "route_qr_unavailable": "QR을 표시할 수 없습니다.",
        "route_map_unavailable": "지도를 표시할 수 없습니다.",
        "route_no_image": "이미지가 없습니다.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "여행 스탬프",
        "travel_stamp_line1": "QR을 스캔해 스탬프 투어를 시작하세요.",
        "travel_stamp_line2": "관광지를 돌며 스탬프를 모아보세요.",
        "travel_stamp_line3": "미션을 완료하면 보상을 받을 수 있어요.",
        "travel_stamp_qr_hint": "스캔하여 참여",
    },
    "ja": {
        "location_label": "位置",
        "food_category_title": "料理カテゴリ",
        "route_category_food": "食事",
        "route_category_landmark": "観光地",
        "route_category_restroom": "トイレ",
        "route_category_info": "観光案内",
        "food_no_menus": "利用可能なメニューがありません。",
        "food_no_foods": "表示できる料理がありません。",
        "food_select_prompt": "料理を選ぶと詳細が表示されます。",
        "food_restaurant_info": "店舗情報",
        "food_full_menu": "全メニュー",
        "food_no_description": "説明なし",
        "food_no_additional_info": "追加情報はありません。",
        "food_no_menu_info": "メニュー情報なし",
        "food_price_label": "価格",
        "food_restaurants_title": "レストラン",
        "food_no_restaurants": "利用可能なレストランがありません。",
        "food_restaurant_label": "店舗",
        "food_hours_label": "営業時間",
        "food_phone_label": "電話",
        "food_reservation_label": "予約",
        "food_address_label": "住所",
        "food_menu_fallback": "メニュー",
        "place_fallback": "場所 {id}",
        "landmarks_empty": "利用可能な観光地がありません。",
        "route_qr_unavailable": "QRを表示できません。",
        "route_map_unavailable": "地図を表示できません。",
        "route_no_image": "画像がありません。",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "トラベルスタンプ",
        "travel_stamp_line1": "QRをスキャンしてスタンプツアーを始めましょう。",
        "travel_stamp_line2": "観光地を巡ってスタンプを集めてください。",
        "travel_stamp_line3": "ミッションを達成すると報酬がもらえます。",
        "travel_stamp_qr_hint": "スキャンして参加",
    },
    "zh-CN": {
        "location_label": "位置",
        "food_category_title": "美食分类",
        "route_category_food": "美食",
        "route_category_landmark": "景点",
        "route_category_restroom": "卫生间",
        "route_category_info": "旅游信息",
        "food_no_menus": "暂无可用菜单。",
        "food_no_foods": "暂无可显示的美食。",
        "food_select_prompt": "选择美食可查看详情。",
        "food_restaurant_info": "店铺信息",
        "food_full_menu": "完整菜单",
        "food_no_description": "暂无说明",
        "food_no_additional_info": "暂无其他信息。",
        "food_no_menu_info": "无菜单信息",
        "food_price_label": "价格",
        "food_restaurants_title": "餐厅",
        "food_no_restaurants": "暂无可用餐厅。",
        "food_restaurant_label": "店铺",
        "food_hours_label": "营业时间",
        "food_phone_label": "电话",
        "food_reservation_label": "预订",
        "food_address_label": "地址",
        "food_menu_fallback": "菜单",
        "place_fallback": "地点 {id}",
        "landmarks_empty": "暂无可用景点。",
        "route_qr_unavailable": "无法显示QR。",
        "route_map_unavailable": "无法显示地图。",
        "route_no_image": "没有图片。",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "旅行集章",
        "travel_stamp_line1": "扫描二维码开始集章之旅。",
        "travel_stamp_line2": "游览景点并收集印章。",
        "travel_stamp_line3": "完成任务即可获得奖励。",
        "travel_stamp_qr_hint": "扫码参与",
    },
    "zh-TW": {
        "location_label": "位置",
        "food_category_title": "美食分類",
        "route_category_food": "美食",
        "route_category_landmark": "景點",
        "route_category_restroom": "洗手間",
        "route_category_info": "旅遊資訊",
        "food_no_menus": "目前沒有可用菜單。",
        "food_no_foods": "沒有可顯示的美食。",
        "food_select_prompt": "選擇美食可查看詳情。",
        "food_restaurant_info": "店家資訊",
        "food_full_menu": "完整菜單",
        "food_no_description": "沒有說明",
        "food_no_additional_info": "沒有其他資訊。",
        "food_no_menu_info": "無菜單資訊",
        "food_price_label": "價格",
        "food_restaurants_title": "餐廳",
        "food_no_restaurants": "目前沒有可用餐廳。",
        "food_restaurant_label": "店家",
        "food_hours_label": "營業時間",
        "food_phone_label": "電話",
        "food_reservation_label": "預訂",
        "food_address_label": "地址",
        "food_menu_fallback": "菜單",
        "place_fallback": "地點 {id}",
        "landmarks_empty": "目前沒有可用景點。",
        "route_qr_unavailable": "無法顯示QR。",
        "route_map_unavailable": "無法顯示地圖。",
        "route_no_image": "沒有圖片。",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "旅行集章",
        "travel_stamp_line1": "掃描 QR 碼開始集章之旅。",
        "travel_stamp_line2": "走訪景點並收集印章。",
        "travel_stamp_line3": "完成任務即可獲得獎勵。",
        "travel_stamp_qr_hint": "掃碼參加",
    },
    "de": {
        "location_label": "Standort",
        "food_category_title": "Essenskategorien",
        "route_category_food": "Essen",
        "route_category_landmark": "Sehenswürdigkeiten",
        "route_category_restroom": "Toiletten",
        "route_category_info": "Touristeninfo",
        "food_no_menus": "Keine Menüs verfügbar.",
        "food_no_foods": "Keine Speisen verfügbar.",
        "food_select_prompt": "Wählen Sie ein Gericht, um Details zu sehen.",
        "food_restaurant_info": "Restaurantinfo",
        "food_full_menu": "Gesamtes Menü",
        "food_no_description": "Keine Beschreibung",
        "food_no_additional_info": "Keine zusätzlichen Informationen.",
        "food_no_menu_info": "Keine Menüinformationen",
        "food_price_label": "Preis",
        "food_restaurants_title": "Restaurants",
        "food_no_restaurants": "Keine Restaurants verfügbar.",
        "food_restaurant_label": "Restaurant",
        "food_hours_label": "Öffnungszeiten",
        "food_phone_label": "Telefon",
        "food_reservation_label": "Reservierung",
        "food_address_label": "Adresse",
        "food_menu_fallback": "Menü",
        "place_fallback": "Ort {id}",
        "landmarks_empty": "Keine Sehenswürdigkeiten verfügbar.",
        "route_qr_unavailable": "QR nicht verfügbar.",
        "route_map_unavailable": "Karte nicht verfügbar.",
        "route_no_image": "Kein Bild.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Reisestempel",
        "travel_stamp_line1": "Scannen Sie den QR-Code, um Ihre Stempel-Tour zu starten.",
        "travel_stamp_line2": "Sammeln Sie Stempel, während Sie Sehenswürdigkeiten besuchen.",
        "travel_stamp_line3": "Schließen Sie Missionen ab und erhalten Sie Belohnungen.",
        "travel_stamp_qr_hint": "Scannen, um teilzunehmen",
    },
    "nl": {
        "location_label": "Locatie",
        "food_category_title": "Eetcategorieën",
        "route_category_food": "Eten",
        "route_category_landmark": "Bezienswaardigheden",
        "route_category_restroom": "Toiletten",
        "route_category_info": "Toeristische info",
        "food_no_menus": "Geen menu's beschikbaar.",
        "food_no_foods": "Geen gerechten beschikbaar.",
        "food_select_prompt": "Selecteer een gerecht om details te bekijken.",
        "food_restaurant_info": "Restaurantinfo",
        "food_full_menu": "Volledig menu",
        "food_no_description": "Geen beschrijving",
        "food_no_additional_info": "Geen extra informatie.",
        "food_no_menu_info": "Geen menu-informatie",
        "food_price_label": "Prijs",
        "food_restaurants_title": "Restaurants",
        "food_no_restaurants": "Geen restaurants beschikbaar.",
        "food_restaurant_label": "Restaurant",
        "food_hours_label": "Openingstijden",
        "food_phone_label": "Telefoon",
        "food_reservation_label": "Reservering",
        "food_address_label": "Adres",
        "food_menu_fallback": "Menu",
        "place_fallback": "Locatie {id}",
        "landmarks_empty": "Geen bezienswaardigheden beschikbaar.",
        "route_qr_unavailable": "QR niet beschikbaar.",
        "route_map_unavailable": "Kaart niet beschikbaar.",
        "route_no_image": "Geen afbeelding.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Reisstempel",
        "travel_stamp_line1": "Scan de QR-code om je stempeltocht te starten.",
        "travel_stamp_line2": "Verzamel stempels terwijl je bezienswaardigheden bezoekt.",
        "travel_stamp_line3": "Voltooi missies en ontvang beloningen.",
        "travel_stamp_qr_hint": "Scan om mee te doen",
    },
    "sv": {
        "location_label": "Plats",
        "food_category_title": "Matkategorier",
        "route_category_food": "Mat",
        "route_category_landmark": "Sevärdheter",
        "route_category_restroom": "Toaletter",
        "route_category_info": "Turistinformation",
        "food_no_menus": "Inga menyer tillgängliga.",
        "food_no_foods": "Inga rätter tillgängliga.",
        "food_select_prompt": "Välj en rätt för att se detaljer.",
        "food_restaurant_info": "Restauranginfo",
        "food_full_menu": "Hela menyn",
        "food_no_description": "Ingen beskrivning",
        "food_no_additional_info": "Ingen ytterligare information.",
        "food_no_menu_info": "Ingen menyinformation",
        "food_price_label": "Pris",
        "food_restaurants_title": "Restauranger",
        "food_no_restaurants": "Inga restauranger tillgängliga.",
        "food_restaurant_label": "Restaurang",
        "food_hours_label": "Öppettider",
        "food_phone_label": "Telefon",
        "food_reservation_label": "Bokning",
        "food_address_label": "Adress",
        "food_menu_fallback": "Meny",
        "place_fallback": "Plats {id}",
        "landmarks_empty": "Inga sevärdheter tillgängliga.",
        "route_qr_unavailable": "QR ej tillgänglig.",
        "route_map_unavailable": "Karta ej tillgänglig.",
        "route_no_image": "Ingen bild.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Resestämpel",
        "travel_stamp_line1": "Skanna QR-koden för att starta din stämpeltur.",
        "travel_stamp_line2": "Samla stämplar när du besöker sevärdheter.",
        "travel_stamp_line3": "Slutför uppdrag för att få belöningar.",
        "travel_stamp_qr_hint": "Skanna för att delta",
    },
    "fr": {
        "location_label": "Emplacement",
        "food_category_title": "Catégories de nourriture",
        "route_category_food": "Nourriture",
        "route_category_landmark": "Sites touristiques",
        "route_category_restroom": "Toilettes",
        "route_category_info": "Info touristique",
        "food_no_menus": "Aucun menu disponible.",
        "food_no_foods": "Aucun plat disponible.",
        "food_select_prompt": "Sélectionnez un plat pour voir les détails.",
        "food_restaurant_info": "Infos du restaurant",
        "food_full_menu": "Menu complet",
        "food_no_description": "Pas de description",
        "food_no_additional_info": "Aucune information supplémentaire.",
        "food_no_menu_info": "Aucune info sur le menu",
        "food_price_label": "Prix",
        "food_restaurants_title": "Restaurants",
        "food_no_restaurants": "Aucun restaurant disponible.",
        "food_restaurant_label": "Restaurant",
        "food_hours_label": "Horaires",
        "food_phone_label": "Téléphone",
        "food_reservation_label": "Réservation",
        "food_address_label": "Adresse",
        "food_menu_fallback": "Menu",
        "place_fallback": "Lieu {id}",
        "landmarks_empty": "Aucun site touristique disponible.",
        "route_qr_unavailable": "QR indisponible.",
        "route_map_unavailable": "Carte indisponible.",
        "route_no_image": "Aucune image.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Tampon de voyage",
        "travel_stamp_line1": "Scannez le QR code pour démarrer votre parcours de tampons.",
        "travel_stamp_line2": "Collectez des tampons en visitant les sites.",
        "travel_stamp_line3": "Terminez des missions pour obtenir des récompenses.",
        "travel_stamp_qr_hint": "Scannez pour participer",
    },
    "it": {
        "location_label": "Posizione",
        "food_category_title": "Categorie di cibo",
        "route_category_food": "Cibo",
        "route_category_landmark": "Attrazioni",
        "route_category_restroom": "Servizi igienici",
        "route_category_info": "Info turistiche",
        "food_no_menus": "Nessun menu disponibile.",
        "food_no_foods": "Nessun piatto disponibile.",
        "food_select_prompt": "Seleziona un piatto per vedere i dettagli.",
        "food_restaurant_info": "Info ristorante",
        "food_full_menu": "Menu completo",
        "food_no_description": "Nessuna descrizione",
        "food_no_additional_info": "Nessuna informazione aggiuntiva.",
        "food_no_menu_info": "Nessuna info sul menu",
        "food_price_label": "Prezzo",
        "food_restaurants_title": "Ristoranti",
        "food_no_restaurants": "Nessun ristorante disponibile.",
        "food_restaurant_label": "Ristorante",
        "food_hours_label": "Orari",
        "food_phone_label": "Telefono",
        "food_reservation_label": "Prenotazione",
        "food_address_label": "Indirizzo",
        "food_menu_fallback": "Menu",
        "place_fallback": "Luogo {id}",
        "landmarks_empty": "Nessuna attrazione disponibile.",
        "route_qr_unavailable": "QR non disponibile.",
        "route_map_unavailable": "Mappa non disponibile.",
        "route_no_image": "Nessuna immagine.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Timbro di viaggio",
        "travel_stamp_line1": "Scansiona il QR per iniziare il tour dei timbri.",
        "travel_stamp_line2": "Raccogli timbri visitando le attrazioni.",
        "travel_stamp_line3": "Completa le missioni per ottenere ricompense.",
        "travel_stamp_qr_hint": "Scansiona per partecipare",
    },
    "es": {
        "location_label": "Ubicación",
        "food_category_title": "Categorías de comida",
        "route_category_food": "Comida",
        "route_category_landmark": "Atracciones",
        "route_category_restroom": "Baños",
        "route_category_info": "Información turística",
        "food_no_menus": "No hay menús disponibles.",
        "food_no_foods": "No hay comidas disponibles.",
        "food_select_prompt": "Selecciona un plato para ver los detalles.",
        "food_restaurant_info": "Información del restaurante",
        "food_full_menu": "Menú completo",
        "food_no_description": "Sin descripción",
        "food_no_additional_info": "No hay información adicional.",
        "food_no_menu_info": "Sin información del menú",
        "food_price_label": "Precio",
        "food_restaurants_title": "Restaurantes",
        "food_no_restaurants": "No hay restaurantes disponibles.",
        "food_restaurant_label": "Restaurante",
        "food_hours_label": "Horario",
        "food_phone_label": "Teléfono",
        "food_reservation_label": "Reserva",
        "food_address_label": "Dirección",
        "food_menu_fallback": "Menú",
        "place_fallback": "Lugar {id}",
        "landmarks_empty": "No hay atracciones disponibles.",
        "route_qr_unavailable": "QR no disponible.",
        "route_map_unavailable": "Mapa no disponible.",
        "route_no_image": "Sin imagen.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Sello de viaje",
        "travel_stamp_line1": "Escanea el QR para comenzar el recorrido de sellos.",
        "travel_stamp_line2": "Recoge sellos mientras visitas las atracciones.",
        "travel_stamp_line3": "Completa misiones para recibir recompensas.",
        "travel_stamp_qr_hint": "Escanea para participar",
    },
    "pt": {
        "location_label": "Localização",
        "food_category_title": "Categorias de comida",
        "route_category_food": "Comida",
        "route_category_landmark": "Atrações",
        "route_category_restroom": "Banheiros",
        "route_category_info": "Informações turísticas",
        "food_no_menus": "Nenhum menu disponível.",
        "food_no_foods": "Nenhuma comida disponível.",
        "food_select_prompt": "Selecione um prato para ver os detalhes.",
        "food_restaurant_info": "Informações do restaurante",
        "food_full_menu": "Menu completo",
        "food_no_description": "Sem descrição",
        "food_no_additional_info": "Sem informações adicionais.",
        "food_no_menu_info": "Sem informações do menu",
        "food_price_label": "Preço",
        "food_restaurants_title": "Restaurantes",
        "food_no_restaurants": "Nenhum restaurante disponível.",
        "food_restaurant_label": "Restaurante",
        "food_hours_label": "Horário",
        "food_phone_label": "Telefone",
        "food_reservation_label": "Reserva",
        "food_address_label": "Endereço",
        "food_menu_fallback": "Menu",
        "place_fallback": "Local {id}",
        "landmarks_empty": "Nenhuma atração disponível.",
        "route_qr_unavailable": "QR indisponível.",
        "route_map_unavailable": "Mapa indisponível.",
        "route_no_image": "Sem imagem.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Carimbo de viagem",
        "travel_stamp_line1": "Escaneie o QR para iniciar o tour de carimbos.",
        "travel_stamp_line2": "Colete carimbos enquanto visita as atrações.",
        "travel_stamp_line3": "Conclua missões para ganhar recompensas.",
        "travel_stamp_qr_hint": "Escaneie para participar",
    },
    "ru": {
        "location_label": "Местоположение",
        "food_category_title": "Категории еды",
        "route_category_food": "Еда",
        "route_category_landmark": "Достопримечательности",
        "route_category_restroom": "Туалеты",
        "route_category_info": "Туристическая информация",
        "food_no_menus": "Меню недоступны.",
        "food_no_foods": "Блюда недоступны.",
        "food_select_prompt": "Выберите блюдо, чтобы увидеть подробности.",
        "food_restaurant_info": "Информация о ресторане",
        "food_full_menu": "Полное меню",
        "food_no_description": "Нет описания",
        "food_no_additional_info": "Дополнительной информации нет.",
        "food_no_menu_info": "Нет информации о меню",
        "food_price_label": "Цена",
        "food_restaurants_title": "Рестораны",
        "food_no_restaurants": "Рестораны недоступны.",
        "food_restaurant_label": "Ресторан",
        "food_hours_label": "Часы работы",
        "food_phone_label": "Телефон",
        "food_reservation_label": "Бронирование",
        "food_address_label": "Адрес",
        "food_menu_fallback": "Меню",
        "place_fallback": "Место {id}",
        "landmarks_empty": "Достопримечательности недоступны.",
        "route_qr_unavailable": "QR недоступен.",
        "route_map_unavailable": "Карта недоступна.",
        "route_no_image": "Нет изображения.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Путевой штамп",
        "travel_stamp_line1": "Сканируйте QR-код, чтобы начать тур со штампами.",
        "travel_stamp_line2": "Собирайте штампы, посещая достопримечательности.",
        "travel_stamp_line3": "Выполняйте задания и получайте награды.",
        "travel_stamp_qr_hint": "Сканируйте для участия",
    },
    "pl": {
        "location_label": "Lokalizacja",
        "food_category_title": "Kategorie jedzenia",
        "route_category_food": "Jedzenie",
        "route_category_landmark": "Atrakcje",
        "route_category_restroom": "Toalety",
        "route_category_info": "Informacja turystyczna",
        "food_no_menus": "Brak dostępnych menu.",
        "food_no_foods": "Brak dostępnych potraw.",
        "food_select_prompt": "Wybierz danie, aby zobaczyć szczegóły.",
        "food_restaurant_info": "Informacje o restauracji",
        "food_full_menu": "Pełne menu",
        "food_no_description": "Brak opisu",
        "food_no_additional_info": "Brak dodatkowych informacji.",
        "food_no_menu_info": "Brak informacji o menu",
        "food_price_label": "Cena",
        "food_restaurants_title": "Restauracje",
        "food_no_restaurants": "Brak dostępnych restauracji.",
        "food_restaurant_label": "Restauracja",
        "food_hours_label": "Godziny",
        "food_phone_label": "Telefon",
        "food_reservation_label": "Rezerwacja",
        "food_address_label": "Adres",
        "food_menu_fallback": "Menu",
        "place_fallback": "Miejsce {id}",
        "landmarks_empty": "Brak dostępnych atrakcji.",
        "route_qr_unavailable": "QR niedostępny.",
        "route_map_unavailable": "Mapa niedostępna.",
        "route_no_image": "Brak obrazu.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Stempel podróżny",
        "travel_stamp_line1": "Zeskanuj kod QR, aby rozpocząć trasę ze stemplami.",
        "travel_stamp_line2": "Zbieraj stemple podczas zwiedzania atrakcji.",
        "travel_stamp_line3": "Wykonuj misje i odbieraj nagrody.",
        "travel_stamp_qr_hint": "Zeskanuj, aby dołączyć",
    },
    "cs": {
        "location_label": "Poloha",
        "food_category_title": "Kategorie jídla",
        "route_category_food": "Jídlo",
        "route_category_landmark": "Památky",
        "route_category_restroom": "Toalety",
        "route_category_info": "Turistické informace",
        "food_no_menus": "Žádná menu nejsou k dispozici.",
        "food_no_foods": "Žádná jídla nejsou k dispozici.",
        "food_select_prompt": "Vyberte jídlo pro zobrazení detailů.",
        "food_restaurant_info": "Informace o restauraci",
        "food_full_menu": "Celé menu",
        "food_no_description": "Žádný popis",
        "food_no_additional_info": "Žádné další informace.",
        "food_no_menu_info": "Žádné informace o menu",
        "food_price_label": "Cena",
        "food_restaurants_title": "Restaurace",
        "food_no_restaurants": "Žádné restaurace nejsou k dispozici.",
        "food_restaurant_label": "Restaurace",
        "food_hours_label": "Otevírací doba",
        "food_phone_label": "Telefon",
        "food_reservation_label": "Rezervace",
        "food_address_label": "Adresa",
        "food_menu_fallback": "Menu",
        "place_fallback": "Místo {id}",
        "landmarks_empty": "Žádné památky nejsou k dispozici.",
        "route_qr_unavailable": "QR není k dispozici.",
        "route_map_unavailable": "Mapa není k dispozici.",
        "route_no_image": "Žádný obrázek.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Cestovní razítko",
        "travel_stamp_line1": "Naskenujte QR kód a začněte razítkovou trasu.",
        "travel_stamp_line2": "Sbírejte razítka při návštěvě památek.",
        "travel_stamp_line3": "Splňte mise a získejte odměny.",
        "travel_stamp_qr_hint": "Naskenujte a zapojte se",
    },
    "uk": {
        "location_label": "Розташування",
        "food_category_title": "Категорії їжі",
        "route_category_food": "Їжа",
        "route_category_landmark": "Пам'ятки",
        "route_category_restroom": "Туалети",
        "route_category_info": "Туристична інформація",
        "food_no_menus": "Меню недоступні.",
        "food_no_foods": "Страви недоступні.",
        "food_select_prompt": "Виберіть страву, щоб переглянути деталі.",
        "food_restaurant_info": "Інформація про ресторан",
        "food_full_menu": "Повне меню",
        "food_no_description": "Без опису",
        "food_no_additional_info": "Додаткової інформації немає.",
        "food_no_menu_info": "Немає інформації про меню",
        "food_price_label": "Ціна",
        "food_restaurants_title": "Ресторани",
        "food_no_restaurants": "Ресторани недоступні.",
        "food_restaurant_label": "Ресторан",
        "food_hours_label": "Години роботи",
        "food_phone_label": "Телефон",
        "food_reservation_label": "Бронювання",
        "food_address_label": "Адреса",
        "food_menu_fallback": "Меню",
        "place_fallback": "Місце {id}",
        "landmarks_empty": "Пам'ятки недоступні.",
        "route_qr_unavailable": "QR недоступний.",
        "route_map_unavailable": "Мапа недоступна.",
        "route_no_image": "Немає зображення.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Подорожній штамп",
        "travel_stamp_line1": "Скануйте QR-код, щоб розпочати тур зі штампами.",
        "travel_stamp_line2": "Збирайте штампи, відвідуючи пам'ятки.",
        "travel_stamp_line3": "Виконуйте місії та отримуйте винагороди.",
        "travel_stamp_qr_hint": "Скануйте, щоб приєднатися",
    },
    "lt": {
        "location_label": "Vieta",
        "food_category_title": "Maisto kategorijos",
        "route_category_food": "Maistas",
        "route_category_landmark": "Lankytinos vietos",
        "route_category_restroom": "Tualetai",
        "route_category_info": "Turistinė informacija",
        "food_no_menus": "Nėra galimų meniu.",
        "food_no_foods": "Nėra galimų patiekalų.",
        "food_select_prompt": "Pasirinkite patiekalą, kad pamatytumėte detales.",
        "food_restaurant_info": "Restorano informacija",
        "food_full_menu": "Pilnas meniu",
        "food_no_description": "Nėra aprašymo",
        "food_no_additional_info": "Nėra papildomos informacijos.",
        "food_no_menu_info": "Nėra meniu informacijos",
        "food_price_label": "Kaina",
        "food_restaurants_title": "Restoranai",
        "food_no_restaurants": "Nėra galimų restoranų.",
        "food_restaurant_label": "Restoranas",
        "food_hours_label": "Darbo laikas",
        "food_phone_label": "Telefonas",
        "food_reservation_label": "Rezervacija",
        "food_address_label": "Adresas",
        "food_menu_fallback": "Meniu",
        "place_fallback": "Vieta {id}",
        "landmarks_empty": "Nėra lankytinų vietų.",
        "route_qr_unavailable": "QR nepasiekiamas.",
        "route_map_unavailable": "Žemėlapis nepasiekiamas.",
        "route_no_image": "Nėra vaizdo.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Kelionės antspaudas",
        "travel_stamp_line1": "Nuskenuokite QR kodą ir pradėkite antspaudų turą.",
        "travel_stamp_line2": "Rinkite antspaudus lankydami lankytinas vietas.",
        "travel_stamp_line3": "Įvykdykite misijas ir gaukite apdovanojimų.",
        "travel_stamp_qr_hint": "Nuskenuokite, kad prisijungtumėte",
    },
    "lv": {
        "location_label": "Atrašanās vieta",
        "food_category_title": "Ēdienu kategorijas",
        "route_category_food": "Ēdiens",
        "route_category_landmark": "Apskates vietas",
        "route_category_restroom": "Tualetes",
        "route_category_info": "Tūrisma informācija",
        "food_no_menus": "Nav pieejamu izvēlņu.",
        "food_no_foods": "Nav pieejamu ēdienu.",
        "food_select_prompt": "Izvēlieties ēdienu, lai redzētu detaļas.",
        "food_restaurant_info": "Restorāna informācija",
        "food_full_menu": "Pilna ēdienkarte",
        "food_no_description": "Nav apraksta",
        "food_no_additional_info": "Nav papildu informācijas.",
        "food_no_menu_info": "Nav informācijas par ēdienkarti",
        "food_price_label": "Cena",
        "food_restaurants_title": "Restorāni",
        "food_no_restaurants": "Nav pieejamu restorānu.",
        "food_restaurant_label": "Restorāns",
        "food_hours_label": "Darba laiks",
        "food_phone_label": "Tālrunis",
        "food_reservation_label": "Rezervācija",
        "food_address_label": "Adrese",
        "food_menu_fallback": "Ēdienkarte",
        "place_fallback": "Vieta {id}",
        "landmarks_empty": "Nav pieejamu apskates vietu.",
        "route_qr_unavailable": "QR nav pieejams.",
        "route_map_unavailable": "Karte nav pieejama.",
        "route_no_image": "Nav attēla.",
        "route_google_maps": "Google Maps",
        "travel_stamp_title": "Ceļojuma zīmogs",
        "travel_stamp_line1": "Noskenējiet QR kodu, lai sāktu zīmogu tūri.",
        "travel_stamp_line2": "Vāciet zīmogus, apmeklējot apskates vietas.",
        "travel_stamp_line3": "Pabeidziet misijas un saņemiet balvas.",
        "travel_stamp_qr_hint": "Noskenējiet, lai pievienotos",
    },
}

LANG_FLAG_TO_PLACE_CODE = {
    "KR": "ko",
    "US": "en",
    "JP": "ja",
    "CN": "zh",
    "TW": "zh",
}


def _place_lang_code(lang: str) -> str:
    info = LANG_INFO.get(lang, LANG_INFO.get("English", {}))
    flag = info.get("flags", "")
    return LANG_FLAG_TO_PLACE_CODE.get(flag, "en")


def _menu_lang_code(lang: str) -> str:
    info = LANG_INFO.get(lang, LANG_INFO.get("English", {}))
    flag = info.get("flags", "")
    mapping = {
        "KR": "ko",
        "US": "en",
        "JP": "ja",
        "CN": "zh-CN",
        "TW": "zh-TW",
        "DE": "de",
        "NL": "nl",
        "SV": "sv",
        "SE": "sv",
        "FR": "fr",
        "IT": "it",
        "ES": "es",
        "PT": "pt",
        "RU": "ru",
        "PL": "pl",
        "CZ": "cs",
        "UA": "uk",
        "LT": "lt",
        "LV": "lv",
    }
    return mapping.get(flag, "en")


def _lang_value(lang: str, key: str, default: str) -> str:
    fallback = LANG_INFO.get("English", {})
    info = LANG_INFO.get(lang, fallback)
    if key in info:
        return info[key]
    ui_value = UI_TRANSLATIONS.get(_menu_lang_code(lang), {}).get(key)
    if ui_value is not None:
        return ui_value
    return fallback.get(key, default)


def _resolve_place_image_path(url: str):
    if not url:
        return None
    path = Path(url)
    if path.is_absolute():
        return path if path.exists() else None
    candidates = [
        (PROJECT_DIR / path).resolve(),
    ]
    base_dir = PLACE_IMAGE_DIR if PLACE_IMAGE_DIR.exists() else DEFAULT_IMAGE_DIR
    if base_dir:
        candidates.append((base_dir / path).resolve())
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def _get_cached_pixmap(image_path: Path, size: QSize, keep_aspect: bool = True):
    if not image_path or not size or not size.isValid():
        return None
    key = (str(image_path), size.width(), size.height(), keep_aspect)
    cached = _IMAGE_PIXMAP_CACHE.get(key)
    if cached is not None:
        return cached
    pixmap = QPixmap(str(image_path))
    if pixmap.isNull():
        return None
    mode = Qt.KeepAspectRatio if keep_aspect else Qt.IgnoreAspectRatio
    scaled = pixmap.scaled(size, mode, Qt.SmoothTransformation)
    if len(_IMAGE_PIXMAP_CACHE) >= _IMAGE_PIXMAP_CACHE_MAX:
        _IMAGE_PIXMAP_CACHE.pop(next(iter(_IMAGE_PIXMAP_CACHE)))
    _IMAGE_PIXMAP_CACHE[key] = scaled
    return scaled


def _set_back_button_icon(button, tooltip: str) -> None:
    size = 24
    ratio = button.devicePixelRatioF() if hasattr(button, "devicePixelRatioF") else 1.0
    pixmap = QPixmap(int(size * ratio), int(size * ratio))
    pixmap.setDevicePixelRatio(ratio)
    pixmap.fill(Qt.transparent)

    color = button.palette().color(QPalette.ButtonText)
    pen = QPen(color, 2.2, Qt.SolidLine, Qt.RoundCap, Qt.RoundJoin)
    painter = QPainter(pixmap)
    painter.setRenderHint(QPainter.Antialiasing, True)
    painter.setPen(pen)

    path = QPainterPath()
    path.moveTo(size * 0.65, size * 0.2)
    path.lineTo(size * 0.35, size * 0.5)
    path.lineTo(size * 0.65, size * 0.8)
    painter.drawPath(path)
    painter.end()

    button.setIcon(QIcon(pixmap))
    button.setIconSize(QSize(size, size))
    button.setText("")
    button.setToolTip(tooltip)

def _build_qr_pixmap(url: str, size: int):
    if not url:
        return None
    try:
        import qrcode
        from PIL import Image
    except Exception:
        return None

    qr = qrcode.QRCode(border=1, box_size=10)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    img = img.resize((size, size), Image.NEAREST)
    img = img.convert("RGBA")
    data = img.tobytes("raw", "RGBA")
    qimage = QImage(data, img.size[0], img.size[1], QImage.Format_RGBA8888)
    return QPixmap.fromImage(qimage)
